meta_product_name: "Bithesis"
meta_title: "Bithesis - Desarrollar tu tesis si es posible"
meta_description: "Bi.Thesis es una plataforma que brinda planes de acompañamiento personalizado para el desarrollo de un proyecto de investigación, así como cursos especializados y recursos de libre disposición para el público en general, con la visión de que el impacto generado por las investigaciones ayudará a las personas en la realización de sus planes personales, profesionales y a la sociedad"
meta_image: "cover.jpg" # should exist in `app/assets/images/`  # required for Twitter Cards
